# Generated by Django 3.1 on 2020-08-22 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin_Messages',
            new_name='Messages',
        ),
    ]
