# Generated by Django 3.1 on 2020-08-22 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0002_auto_20200822_1734'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Messages',
            new_name='Message',
        ),
        migrations.RenameModel(
            old_name='RegularPatients',
            new_name='RegularPatient',
        ),
    ]
