# Generated by Django 3.1 on 2020-08-22 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20200822_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='regularpatient',
            old_name='completed',
            new_name='alert',
        ),
        migrations.AlterField(
            model_name='regularpatient',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='regularpatient',
            name='regularMedicines',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='regularpatient',
            name='repeat_schedule',
            field=models.IntegerField(),
        ),
    ]
