# Generated by Django 3.1 on 2020-08-23 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20200822_1747'),
    ]

    operations = [
        migrations.CreateModel(
            name='Test',
            fields=[
                ('row_id', models.AutoField(primary_key=True, serialize=False)),
                ('message', models.CharField(max_length=64)),
                ('time_now', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
