# Generated by Django 3.1 on 2020-08-23 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0005_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='regularpatient',
            name='purchase_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
