# Generated by Django 3.1 on 2020-08-25 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0006_regularpatient_purchase_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappCustomer',
            fields=[
                ('cus_id', models.AutoField(primary_key=True, serialize=False)),
                ('firstName', models.CharField(max_length=64)),
                ('lastName', models.CharField(blank=True, max_length=64, null=True)),
                ('birthdate', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=12, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=64, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='regularpatient',
            name='purchase_date',
            field=models.DateTimeField(),
        ),
    ]
