# Generated by Django 3.1 on 2020-09-23 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0008_auto_20200825_1718'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('product_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=512)),
                ('company_name', models.CharField(max_length=512)),
                ('mrp', models.IntegerField()),
                ('wholesale', models.IntegerField()),
                ('margin', models.FloatField()),
                ('agency_name', models.CharField(max_length=512)),
                ('purchase_date', models.DateTimeField()),
            ],
        ),
        migrations.AlterField(
            model_name='whatsappcustomer',
            name='lastName',
            field=models.CharField(default='NULL', max_length=64),
            preserve_default=False,
        ),
    ]
