# Generated by Django 3.1 on 2020-09-23 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0009_auto_20200923_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='purchase_date',
            field=models.DateField(),
        ),
    ]
