# Generated by Django 3.1 on 2020-09-23 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0010_auto_20200923_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='agency_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='company_name',
            field=models.CharField(blank=True, max_length=512, null=True),
        ),
    ]
