# Generated by Django 3.1 on 2020-09-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0011_auto_20200923_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='wholesale',
            new_name='wholesale_rate',
        ),
        migrations.AddField(
            model_name='product',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_code'),
        ),
    ]
