# Generated by Django 3.1 on 2020-09-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0013_auto_20200923_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='mrp',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='product',
            name='wholesale_rate',
            field=models.FloatField(),
        ),
    ]
